# Background and foreground colors
background = #000000
foreground = #F2F6FD

# Standard colors
palette = 0=#000000
palette = 1=#9a87c1
palette = 2=#77cbfb
palette = 3=#8affff
palette = 4=#647bb7
palette = 5=#9f9ff0
palette = 6=#8eddff
palette = 7=#F2F6FD

# Bright colors
palette = 8=#686163
palette = 9=#b299e2
palette = 10=#72e4ff
palette = 11=#68ffff
palette = 12=#748fda
palette = 13=#b3b1ff
palette = 14=#91f5ff
palette = 15=#f1f5ff
