background            #000000
foreground            #F2F6FD

# black
color0  #000000
color8  #686163

# red
color1  #9a87c1
color9  #b299e2

# green
color2  #77cbfb
color10 #72e4ff

# yellow
color3  #8affff
color11 #68ffff

# blue
color4  #647bb7
color12 #748fda

# magenta
color5  #9f9ff0
color13 #b3b1ff

#cyan
color6  #8eddff
color14 #91f5ff

#white
color7  #F2F6FD
color15 #f1f5ff


